import './styles/style.css';

let arrayDisp = [
  { id: "player1", name: "Vinicius Jr", shirt:'20', position: 'ATA', nposition: 1, },
  { id: "player2", name: "Richarlison", shirt:'09', position: 'ATA', nposition: 1, },
  { id: "player3", name: "Raphinha", shirt:'11', position: 'ATA', nposition: 1, },
  { id: "player4", name: "Neymar Jr", shirt:'10', position: 'ATA', nposition: 1  },
  { id: "player5", name: "Paqueta", shirt:'07', position: 'MEI', nposition: 2 },
  { id: "player6", name: "Casemiro", shirt:'05', position: 'MEI', nposition: 2  },
  { id: "player7", name: "Danilo", shirt:'02', position: 'LAT', nposition: 3  },
  { id: "player8", name: "E. Militão", shirt:'14', position: 'LAT', nposition: 3  },
  { id: "player9", name: "T. Silva", shirt:'03', position: 'ZAG', nposition: 4  },
  { id: "player10", name: "Marquinhos", shirt:'4', position: 'ZAG', nposition: 4, image:"./imagens/alisson.jpg" },
  { id: "player11", name: "Alisson", shirt:'01', position: 'GOL', nposition: 5  },
  { id: "player12", name: "Messi", shirt:'10', position: 'ATA', nposition: 1  },
  { id: "player13", name: "C. Ronaldo", shirt:'07', position: 'ATA', nposition: 1  },
  { id: "player14", name: "Modric", shirt:'10', position: 'MEI', nposition: 2  },
  { id: "player15", name: "Fagner", shirt:'23', position: 'LAT', nposition: 3  },
  { id: "player16", name: "S. Ramos", shirt:'04', position: 'ZAG', nposition: 4  },
  { id: "player17", name: "D.Alaba", shirt:'04', position: 'ZAG', nposition: 4  },
  { id: "player18", name: "Mbappe", shirt:'07', position: 'ATA', nposition: 1  },
  { id: "player19", name: "Grieszman", shirt:'10', position: 'MEI', nposition: 2  },
  { id: "player20", name: "Halland", shirt:'09', position: 'ATA', nposition: 1  },
  { id: "player21", name: "Alphonso Davies", shirt:'19', position: 'LAT', nposition: 3  },
  { id: "player22", name: "Antony", shirt:'21', position: 'ATA', nposition: 1  },
  { id: "player23", name: "Rodrygo", shirt:'19', position: 'MEI', nposition: 2  },
  { id: "player24", name: "kvaratskeila", shirt:'77', position: 'ATA', nposition: 1},
  { id: "player25", name: "R.Leao", shirt:'17', position: 'ATA', nposition: 1},
  { id: "player26", name: "Courtois", shirt:'01', position: 'GOL', nposition: 5 }